### ISSUE TITLE
Error when trying to retrieve data from the network

### ISSUE THREAD

**Issue by blaired** [stuartridout/teamlink#10]
When moving through the screens I get this error Error when trying to retrieve data from the network and when pinning a colleague I get Office365Users.UserProfileV2 failed: The method 'UserProfileV2' has an invalid value for parameter 'id'

**Comment by stuartridout** [comment]
This has now been fixed as part of the 1.0.0.18 release.  See [https://github.com/stuartridout/teamlink/releases/tag/v1.18-main](https://github.com/stuartridout/teamlink/releases/tag/v1.18-main)
