### ISSUE TITLE
Update version number to 1.0.0.17

### ISSUE THREAD

**Issue by petepuu** [stuartridout/teamlink#12]
Version number in the App > OnStart is wrong

<img width="407" alt="image" src="https://user-images.githubusercontent.com/8307644/155716056-aa8d7d8b-7127-495d-9793-9648c618ffbd.png">

**Comment by stuartridout** [comment]
This has now been fixed as part of the 1.0.0.18 release.  See [https://github.com/stuartridout/teamlink/releases/tag/v1.18-main](https://github.com/stuartridout/teamlink/releases/tag/v1.18-main)
