### ISSUE TITLE
Error when trying to retrieve data from the network

### ISSUE THREAD

**Issue by GarryPope** [stuartridout/teamlink#13]
Hello @stuartridout,

I hope you're well. Can you help me please?

We just created a new team and installed your solution: v1.17

We are noticing when a user first uses the app they are presented with errors on each screen of "Error when trying to retrieve data from the network."

If I click the x in the top right the banner disappears and I'm able to select the data correctly, and then I no longer receive the error on each screen and the app works fine.

Any ideas why this is happening please? Thanks very much.

![image](https://user-images.githubusercontent.com/68440710/156006099-0a410f78-1f2d-4f34-9edc-0ed995d14384.png)

**Comment by stuartridout** [comment]
This has now been fixed as part of the 1.0.0.18 release.  See [https://github.com/stuartridout/teamlink/releases/tag/v1.18-main](https://github.com/stuartridout/teamlink/releases/tag/v1.18-main)

**Comment by GusChessman** [comment]
Hi stuart, could you share how you handle this error. Im having the same issue on my canvas app in some users.
Ty in advance.
