### ISSUE TITLE
TimezoneOffset error

### ISSUE THREAD

**Issue by GarryPope** [stuartridout/teamlink#14]
Hello @stuartridout,

Sorry, I have another issue. 

I'm receiving an error of "Expected a valid date value as the parameter to "TimezoneOffset" function, received value: null." 

This is happening when I'm trying to view My Site and see who will be in the office on those days. Image below:

Any ideas please? Thanks very much,

Garry

![image](https://user-images.githubusercontent.com/68440710/156006712-57b727c8-9b41-44fc-b1ae-680c778b2aa8.png)

**Comment by stuartridout** [comment]
Hi Garry,  I'm looking into this at the moment.  I'd not seen this before but this is the second occurrence.  I need to check if something has changed to cause this.

**Comment by petepuu** [comment]
Hi, that happens because there is no date selected by default i.e. datetime value = null. I would change it so that when you open the Site view then first day is selected

**Comment by stuartridout** [comment]
Thanks @petepuu - we can't select the first day as a site needs to be selected also, but there is a pending change to handle the error so it doesn't call that function until you click the site.

Hoping to get an update out in the next couple of days.

**Comment by petepuu** [comment]
@stuartridout you can set default for both galleries but I think it is better to not call that function until user selects site and day

**Comment by stuartridout** [comment]
This has now been fixed as part of the 1.0.0.18 release.  See [https://github.com/stuartridout/teamlink/releases/tag/v1.18-main](https://github.com/stuartridout/teamlink/releases/tag/v1.18-main)
