### ISSUE TITLE
Bank Holiday Support

### ISSUE THREAD

**Issue by tdashworth** [stuartridout/teamlink#15]
With the upcoming Bank Holidays in the UK, it would be nice for users not to see these as working days. 

I fully appreciate that handling these _rare_ occurrences can be annoying and, in some cases, some people do work bank holidays. 

Just an idea 😄

**Comment by stuartridout** [comment]
Thanks.  We'll add it to backlog as we would need to consider how this works for all regions so would need to tie this into the country information.

**Comment by slickspidey** [comment]
I know this is closed but could we get an option for to select "Holiday" ourselves as every region and country will be different?
