### ISSUE TITLE
Changing status shows slider with 2 sets of icons

### ISSUE THREAD

**Issue by stephen2423** [stuartridout/teamlink#16]
![Screenshot 2022-05-11 105814](https://user-images.githubusercontent.com/65758117/167823872-7dac5f94-b437-4937-ac04-9c501957181d.png)

When selecting a status, such as Home, Office  or not working, there is a slider under the popup showing 2 sets of the 4 icons and no idea how stop it.  This is on version 1.0.0.19.

**Comment by stuartridout** [comment]
Hi there.  It appears that the app first run experience has run twice creating duplicate entries.   

Go to the Power Apps app in Teams.   If you can see TeamLink on the front page then click to Edit it.

If not then click the Build tab
Select the Team where you have installed it.
Select Installed Apps
Select See All
Find the app and edit it

When in edit mode click the data icon on the left hand side (looks like a cylinder)
Find the Presence Options table
Click the ... and select Edit data
Select the duplicate rows and Delete the records.

This should sort it for you.

**Comment by stephen2423** [comment]
Great instructions. All sorted now many thanks 😊
