### ISSUE TITLE
issue when selecting work status

### ISSUE THREAD

**Issue by abandyt** [stuartridout/teamlink#2]
I have TeamLink installed in our Teams environment.  When I click a date to set the status, the status is updated on the date before the one I have clicked.  I recorded the issue for better clarity.  Please see attached video.

https://user-images.githubusercontent.com/95639562/144876985-41a0de61-5b94-4294-b90f-f9d4fe6875f1.mp4

.

**Comment by abandyt** [comment]
Also, there does not appear to be a way to edit or delete locations once they are added.  Is this something that may come with a new release?

**Comment by abandyt** [comment]
I also just received this error message when attempting to edit the pinned lis
![teamlink error](https://user-images.githubusercontent.com/95639562/144878638-3db99095-9618-42db-bbd4-0269523b59c5.png)
t.

**Comment by stuartridout** [comment]
>  Also, there does not appear to be a way to edit or delete locations once they are added. Is this something that may come with a new release?

Thanks for spotting the Delete/Edit bug.  The buttons are there but are set to not be visible.  Will update this now.

**Comment by stuartridout** [comment]
> I have TeamLink installed in our Teams environment. When I click a date to set the status, the status is updated on the date before the one I have clicked. I recorded the issue for better clarity. Please see attached video.
> 
>  TeamLink.Issue.2021-12-06_10-46-11.mp4 
> .

This is an odd one.  What time zone are you in?  Power Apps assigns dates with a local timezone applies. TeamLink removes any localisation in terms of time zone.  I wonder if that is causing a problem.    Could you email me at stridout@microsoft.com please so I can look into this further.

**Comment by stuartridout** [comment]
Thanks for your feedback.  We have now closed this and it is updated in the latest release.
