### ISSUE TITLE
Some people in our team channel aren't showing up in "This Team" list

### ISSUE THREAD

**Issue by slickspidey** [stuartridout/teamlink#20]
This morning we setup TeamLink in a channel of 118 people but "This Team" list, which is supposed to show everyone in the same Team's channel, seems to limit how many rows are displayed. Right now, only people on my team with names starting from A to S have their rows displayed in "This Team" and then the list cuts off. I can manually find and pin everyone to my "Pinned List" but it would be ideal if everyone can be displayed in "This Team". Is there a fix for this or a way I can make it display unlimited rows?
FIXED THIS ISSUE: I WENT TO THE CODE FOR "btnThisTeam" ADJUSTED THE ROW LIMIT FROM 90 TO 150 ROWS. 

New issue: Although I changed max rows to 150, it only displays 100 and stops there. This cuts off the most recently hired people on our team. How could I fix this so we can show everyone?

**Comment by stuartridout** [comment]
Fixed.
