### ISSUE TITLE
Change size of 'selection' popup to accomodate new items in the list.

### ISSUE THREAD

**Issue by paul-haigh-iaggbs** [stuartridout/teamlink#21]
Hi - we are LOVING teamlink so far!   I needed to add a few additional categories (training, etc), and I've found the table to add the SVG code to, which works fine - but the pop-up doesn't size automatically to additional elements, so you end up with an ugly scroll bar.

Is it possible to make that autosize - or point me to how I fix that for us? (I'm new to PowerApps).

**Comment by stuartridout** [comment]
Hi Paul.  I'll add this to the backlog for the app.   We initially picked four icons as it displays well on mobile.  More than four doesn't really work on a smaller screen.

Could you consider adding some of your categories as office locations? e.g. Training

**Comment by paul-haigh-iaggbs** [comment]
We could do, but the icons are much easier to parse - people are making trips in to see other colleagues, so I'm not sure they would look carefully at the exact office.

We've lived with the scroll bars so far, but we don't really have mobile users - it's all being done on desktop teams clients.

**Comment by stuartridout** [comment]
How many options do you have?  If you had six you could

- open the app in edit mode
- go to the "Edit Presence and View Any Team" screen
- expand the myCalendar_1 gallery
- expand the containerChangeOption_1 container 
- click galOptions_1
- the Template size property is Self.Width/2 by default.   Change the 2 to be half the number of options.  
- if we had six options it would be Self.Width/3

Try that out and see what that looks like. 

![changegal](https://user-images.githubusercontent.com/6738750/182414889-02803d44-7f0e-4d87-a703-e51a559015bd.png)

**Comment by paul-haigh-iaggbs** [comment]
Apologies - I'd not pushed the code

New look: 
![image](https://user-images.githubusercontent.com/92158089/182567077-024261ae-133a-4c5d-9a41-f6093a4c1c6c.png)

So, this worked beautifully :)

**Comment by stuartridout** [comment]
Perfect!  Be aware that you'll need to make that change again if you upgrade the app in the future.  

You'll also need to remove the unmanaged layer to apply the upgrade.  https://docs.microsoft.com/en-us/power-apps/maker/data-platform/solution-layers#remove-an-unmanaged-layer
