### ISSUE TITLE
change of language

### ISSUE THREAD

**Issue by MacArella** [stuartridout/teamlink#22]
lthe app does not have the option to change the language, and to add new default buttons, such as vacations or medical leave

**Comment by stuartridout** [comment]
Hi.  Unfortunately we haven't been able to localise the app with additional languages.   Perhaps in the future. 

We made a conscious decision to not differentiate between leave types.  Most organizations have a dedicated vacation tool and some people don't want to share if they have medical leave.  We originally had the Not Working category listed as vacation  but received feedback that it was too limiting as some people have compassionate leave, medical leave, parental leave etc which all don't count as vacation.
