### ISSUE TITLE
Changing work schedule/location is not working after November 8, 2022

### ISSUE THREAD

**Issue by rpskumar** [stuartridout/teamlink#23]
Changing work schedule is not working as expected after November 1st Week. Steps to reproduce the issue
1. Navigate to any date after November 8
2. Try change Office location , but the App is not allowing to change location
3. Try change work schedule to "Not working" for November 11, But November 10 get updated instead of November 11

**Comment by rpskumar** [comment]
@stuartridout Thank you developing this app and sharing with Community. We deployed the latest version TeamLink 1.0.0.23. Teamlink app is not working after November 8, 2022 dates. Is this issue just in our environment or is it happening to your tenant as well?

**Comment by stuartridout** [comment]
Hi.  This bug has been replicated and is being worked on currently.  It is related to the change in Daylight Savings.

**Comment by rpskumar** [comment]
@stuartridout  Thank you for quick response and confirming the fix is planned.

**Comment by stuartridout** [comment]
There is a pre-release fix for this available at https://github.com/stuartridout/teamlink/releases/tag/v1.27-prerelease along with some other feature enhancements.   This is pre-release so be sure to try in a test environment.

**Comment by rpskumar** [comment]
@stuartridout  Thank you. I updated the latest solution package, the issue is fixed.
