### ISSUE TITLE
The information placed is not displayed within "My Team"

### ISSUE THREAD

**Issue by JhojanR** [stuartridout/teamlink#24]
Nice to greet you Stuar, I have the following problem: I have several users where, when filling in the location of where they will be in the week, it is not displayed in the "My Team" tab. I attached a reference image, hoping you can guide me to a solution.

Thank you very much and greetings.
![afefe57754ad4e558c3dcac07cd30a48](https://user-images.githubusercontent.com/109296783/179012707-b80066f6-ec63-46fd-9e4a-43dc1f933199.png)

**Comment by stuartridout** [comment]
That's very strange.  Is it just when you select Home/Casa?

Can other people see your presence in My Team?

**Comment by JhojanR** [comment]
If I grab the user and drop them into my pinned list, I see their selection with no problem. But within "My team" some selections are not displayed as I show you in the photo. I've already checked some things with the user but I can't find the problem.

**Comment by stuartridout** [comment]
If you refresh the app does it show?

**Comment by JhojanR** [comment]
Not yet, we currently have version 10.0.0.19, if we do the update do you think it will correct the error?

**Comment by stuartridout** [comment]
I would recommend it as it has new functionality but I can see from your screenshot that you've localised the text so perhaps you should install it into a new environment to test how it works for you before committing to do the upgrade as it will remove your changes.

**Comment by stuartridout** [comment]
There is a pre-release available at https://github.com/stuartridout/teamlink/releases/tag/v1.27-prerelease along with some other feature enhancements.   This is pre-release so be sure to try in a test environment.
