### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by SiGroves** [stuartridout/teamlink#25]
Hi
Trying to install from teamlink-main (updated May 19).
See this problem:
The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

Same error also when using Teamlink-1.15-main.zip

**Comment by stuartridout** [comment]
You should be pulling it from the releases - https://github.com/stuartridout/teamlink/releases 

Current version is https://github.com/stuartridout/teamlink/releases/download/v1.23-main/TeamLink_1_0_0_23_managed.zip
