### ISSUE TITLE
Icon for other persons (i.e.: Pinned List) is not resolved when nothing is entered

### ISSUE THREAD

**Issue by mrqrz** [stuartridout/teamlink#26]
Dear Stuart, 

first many thanks for this App!

I just installed it and encountered a small issue:
When another person haven't entered any information for a specific day, it doesn't show any icon.
![TeamLink](https://user-images.githubusercontent.com/57908090/181215719-62ba0b4d-7729-4dd2-b2f0-bdb609a09946.png)

Is there a way to modify the app in order to show the question mark in such cases?

Thank you and Best,
Manuel

**Comment by stuartridout** [comment]
Hi.  This is a bug.  There's a fix coming in the next day or so.
