### ISSUE TITLE
Default Icons in Teams for Desktop are not showing up.

### ISSUE THREAD

**Issue by tomsaudrins** [stuartridout/teamlink#27]
Hi,

First of all, amazing solution! :)

A small issue I have noticed is that if the app is opened through Microsoft Teams, the icon for other people who have not yet set their status is not rendered.

![image](https://user-images.githubusercontent.com/67427155/182091263-2fdb37cd-89ff-4061-ae6b-123ba8dc7826.png)
On PowerApps mobile version, they are shown correctly. 

Not to have to remove the managed solution and install the unmanaged version, is there a missing asset, or did we forgot something in the configuration?

Thank you!

Edit: The issue is also present when the app is opened in the browser.
When opening 'My Profile' it seems that it brings you back to home page, and asks to provide the country, when clicking on bottom right corner "My Profile", but works perfectly when using "Edit button next to profile photo". Might be related to the issue.

**Comment by stuartridout** [comment]
Thanks for the kind words.  With regards to the error … it’s not you it’s me! 

We’ve got a fix available.  It’s available in pre-release right now at https://github.com/stuartridout/teamlink/releases/tag/v1.27-prerelease
