### ISSUE TITLE
 Monday is blank for other members

### ISSUE THREAD

**Issue by rpskumar** [stuartridout/teamlink#29]
Monday is blank for other members. 
<img width="957" alt="TeamAvailability_Monday" src="https://user-images.githubusercontent.com/26256505/183487250-2b725c0e-625e-4536-a9a3-cbd8414ba4df.png">

**Comment by stuartridout** [comment]
What version are you running?

**Comment by rpskumar** [comment]
> What version are you running?

TeamLink_1_0_0_27_managed

**Comment by stuartridout** [comment]
This was fixed in the 1.0.0.30 release.   Could you try updating to that please.

**Comment by rpskumar** [comment]
@stuartridout  I updated 1.0.0.30 solution. The issue is resolved. Thank you
