### ISSUE TITLE
Description for tables

### ISSUE THREAD

**Issue by GarryPope** [stuartridout/teamlink#3]
Hello Stuart,

I hope you are well. Great work on the TeamLink app. You've done a really nice job. I don't have an issue, more a request please. 

Is there any chance you can add a description of what the tables do please? I see for a later release you've included two tables "Audit" and "Version". It would be really helpful if the description would say what all the tables do. It took me a little while previously to piece the tables together and work out what they do.

![image](https://user-images.githubusercontent.com/68440710/145649556-141ab11f-f89b-4888-a8c5-f1fc2648f000.png)

Just a suggestion... Again, nice work, mate!

Garry

**Comment by stuartridout** [comment]
Hi Garry,

Will make sure we do this in the next release.  To answer your question

The audit table records all actions that happen on the app so you can analyse usage of the app.  Most actions are recorded but common actions are

- first time onboarding
- launching the app
- bypassing the disclaimer
- changing status on the app
- clicking the coffee icon to send a message
- viewing who else is on site
- changing work days

The version table is not currently used in Team but it is something that I will often use with apps.  When you update an app sometimes it takes a couple of refreshes by the user before the current version is loaded.  I tend to use the version table to hold the latest version number and when the app launches it compares its version against the database version.  If they're out of sync it shows a message prompting an update.
