### ISSUE TITLE
Question marks aren't showing right in "This team"

### ISSUE THREAD

**Issue by Niiiggo** [stuartridout/teamlink#30]
Hi, 

how can i fix this in the "This team" list? 

![image](https://user-images.githubusercontent.com/110963617/183830406-60adf76a-ed4b-410e-b081-87853df5145c.png)

**Comment by stuartridout** [comment]
What version are you running?  This was fixed in v1.0.0.30

**Comment by Niiiggo** [comment]
Oh ok, we use an older version - sorry. 
Can i download the new version and set it up via power apps and my team? Or how is this working?
