### ISSUE TITLE
Upgrade to .30 is not working

### ISSUE THREAD

**Issue by Niiiggo** [stuartridout/teamlink#31]
Hi, 

I have searched in the closed issues, but [the ](https://github.com/stuartridout/teamlink/issues/17) didn't help me :-( 
I have done the same steps as slickspidey. 

And now I have searched for the unmanaged layer for hours and I don't understand why I can't upgrade my TeamLink version. 

Maybe somebody can help me out of this... 

Thanks!

**Comment by stuartridout** [comment]
Are you saying that you don't have unmanaged layers or you can't find where the unmanaged layers are?

**Comment by Niiiggo** [comment]
I think I have a managed layer. That's what the import windows shows to me. 

I tried to find the "upgrade" button in the import window but that isn't shown to me. In de advanced settings is only the option with the workflow etc. 

And I opened the app from teams, and I have seen the solution are imported, but I have not had the chance to upgrade it there. 

I think my problem is not so clear to understand...
