### ISSUE TITLE
Incorrect Coffee time suggestion

### ISSUE THREAD

**Issue by rpskumar** [stuartridout/teamlink#32]
Issue 1:  Coffee time suggestion. On Aug 23, 2022,  my location is "Work from home" and my Manager work location is "Office". TeamLink suggests for Coffee time. As per my understanding it suppose to suggest for Coffee time only if both in same office/location.
Issue 2: When I click the Coffee icon on Aug 23, the team message comes with previous date (Aug 22) 

My Calendar Setting: Eastern Standard Time
My Manager Calendar Setting: Eastern Standard Time
![image](https://user-images.githubusercontent.com/26256505/184691945-0ebea1ff-e8bf-4cc8-87b3-89912be17191.png)

![image](https://user-images.githubusercontent.com/26256505/184692074-42836250-9063-4725-9c03-93baaa07e94e.png)

**Comment by rpskumar** [comment]
@stuartridout  Thank you for fixing other issues that i reported earlier, Did you get chance to review this issue? Do you experience the same issue. FYI , We are in Eastern Standard Time zone.

**Comment by stuartridout** [comment]
This has now been fixed in the latest version.
