### ISSUE TITLE
Settings Table to hold Text

### ISSUE THREAD

**Issue by Sim2K** [stuartridout/teamlink#34]
Hi Stuart, I have been looking at your TeamLink app and thinking of using it. Its a really well designed app.

While testing, we saw 2 things. You now have a settings table which is great (most my apps run off a global settings/ref table. One table to rule them all) and I was wondering if some of the wording in the app can be set from the settings table. That way we can setup the app to suit us without touching your code. And when you do another update, we won't loose any word changes we have done.

**Comment by stuartridout** [comment]
Hi @Sim2K.  Great shout and is most definitely the direction of travel for the app as we start to get more requests for customisations they are being built into the settings.  

The next big release is focusing on accessibility for screen readers and then the release after is focusing on customisation and personalisation.

**Comment by stuartridout** [comment]
Hi @Sim2K - in the latest release we have included additional languages and all text is now held in a new table Languages.  You can make edits to this to personalise.
