### ISSUE TITLE
Adding new location

### ISSUE THREAD

**Issue by kreed92** [stuartridout/teamlink#39]
Already implementing this app for my team after a Microsoft event last week, but how do I go back and add new office locations after publishing?

**Comment by rpskumar** [comment]
@kreed92  Open Power Apps in Teams  --> Navigate to "Build" Tab --> Select the Team that you published Team Link app --> Locate "Team Link " in Installed App section --> Click on "See All"  
This will open solution explorer. Expand the Tables --> select table "Site" --> Edit Records to add new Location

![image](https://user-images.githubusercontent.com/26256505/189743786-fefaa78e-01fe-4065-8e78-8ee508def22f.png)
