### ISSUE TITLE
changes between teamlink versions

### ISSUE THREAD

**Issue by JhojanR** [stuartridout/teamlink#40]
Hi Stuart,

 I hope you are well. I wanted to ask you something, in our company we have your solution installed, we currently have problems with some users in viewing some lists, we currently have version 1.0.0. What changes has the latest version, are there changes to highlight? 
 
thanks and I look forward to your comments

**Comment by JhojanR** [comment]
any answer?

**Comment by stuartridout** [comment]
Apologies for the delay.  The latest release is 2.0.0.3

All changes are detailed in the releases.
