### ISSUE TITLE
Change icon for location

### ISSUE THREAD

**Issue by Adfri** [stuartridout/teamlink#42]
Hi

Can I change the icons for the locations and also make them a tiny bit smaller?

**Comment by stuartridout** [comment]
The icons are stored in the database as modified SVGs so they can be customised.   To make the icons smaller you’d need to edit the Power App but it is doable.  On 19 Oct 2022, at 12:44, Adfri ***@***.***> wrote:﻿
Hi
Can I change the icons for the locations and also make them a tiny bit smaller?

**Comment by Adfri** [comment]
Thanks! Could you give me a hint as where to find them?

**Comment by Worrelpa** [comment]
Look in the presence option table. That is where SVG info is for each presence option. One is for the coloured icon and the other for the grayed out icon. 

i had to reduce the size of the icons in the gallery as we added a couple of options Just becareful with that as there are X/Y Width/height formulas in the gallery item. So if you move anything byaccident those formulas get overwritten.
