### ISSUE TITLE
Fridays dropped off starting 11/11?

### ISSUE THREAD

**Issue by fgo2023** [stuartridout/teamlink#45]
Hi friends - we started using teamlink at my company and we noticed that Fridays dropped off starting 11/11, any tips on how we can get that fixed?

**Comment by stuartridout** [comment]
Hey friend. What version are you running?On 26 Oct 2022, at 22:38, fgo2023 ***@***.***> wrote:﻿
Hi friends - we started using teamlink at my company and we noticed that Fridays dropped off starting 11/11, any tips on how we can get that fixed?

**Comment by Worrelpa** [comment]
I think it might be related to the one I have just logged. 

Summer time to Winter time zones are offsetting the gallery items date. Currently days fromt he 31st are being offset back on day. So Monday is showing Sundays date. Tuesday is Mondays etc.  Therefore the Fridays information is not showing currently. I should correct itself after the time change this weekend by my logic. However still a bug that needs longterm looking at.

**Comment by Worrelpa** [comment]
one I logged on this https://github.com/stuartridout/teamlink/issues/46

**Comment by fgo2023** [comment]
> Hey friend. What version are you running?On 26 Oct 2022, at 22:38, fgo2023 ***@***.***> wrote:﻿ Hi friends - we started using teamlink at my company and we noticed that Fridays dropped off starting 11/11, any tips on how we can get that fixed? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I am currently running 1.30.2

**Comment by stuartridout** [comment]
Fixed in the latest version
