### ISSUE TITLE
Problems with updating assigned users

### ISSUE THREAD

**Issue by jonathanwadimir** [stuartridout/teamlink#48]
User indicates that they do not update the data of the people assigned to them, they do not see the changes they make or the updates

![image](https://user-images.githubusercontent.com/14363481/204842191-ef846bf4-700f-4fff-958e-81a19f12428d.png)

Usuarios Cristi Saez Elba and Jonathan Jorquera has update the information but don´t update info

**Comment by jonathanwadimir** [comment]
any update?

**Comment by jonathanwadimir** [comment]
Any update for my problem? we can´t work in the plataform by this problem

**Comment by danielagh2022** [comment]
Please your help to correct teamlink. The work team cannot view the days entered by team members

![image](https://user-images.githubusercontent.com/121242742/209171512-bb7f12b5-f8fc-4cbe-8ee0-1fd2237755e2.png)

**Comment by jonathanwadimir** [comment]
yes, it's already working in our organization. but even when we create a new user and assigned a group he can´t config the initial setup

**Comment by jonathanwadimir** [comment]
Dear, is it possible your help for the case?

**Comment by stuartridout** [comment]
I've replied in your other thread.

**Comment by jonathanwadimir** [comment]
can you give me thread id please?

**Comment by stuartridout** [comment]
https://github.com/stuartridout/teamlink/issues/47#issuecomment-1387158012
