### ISSUE TITLE
"This Team" list is now blank in version 2.0

### ISSUE THREAD

**Issue by slickspidey** [stuartridout/teamlink#49]
Hi there,

I just applied the update 2.0 you worked hard on, but now the "This Team" tab/list is empty and I can no longer see all the members of my team without having to pin them. Is there a way to bring it back?

**Comment by stuartridout** [comment]
Working on it now

**Comment by stuartridout** [comment]
[TeamLink_2_0_0_1_managed.zip](https://github.com/stuartridout/teamlink/files/10482540/TeamLink_2_0_0_1_managed.zip)

@slickspidey - can you check this works for you.  There was a filtering error on the buttons.

**Comment by slickspidey** [comment]
> [TeamLink_2_0_0_1_managed.zip](https://github.com/stuartridout/teamlink/files/10482540/TeamLink_2_0_0_1_managed.zip)
> 
> @slickspidey - can you check this works for you. There was a filtering error on the buttons.

@stuartridout that fixed it! Thank you!

Btw, is there a way to display all members of my team in the "This Team" list? It is currently capped at 100 rows, but I have more than 100 team members. I attempted to change the number of rows in the code, but it remains at 100 rows. Or even if there is a way to remove members who don't use it, so it could free up space for other team members?

**Comment by stuartridout** [comment]
[TeamLink_2_0_0_2_managed.zip](https://github.com/stuartridout/teamlink/files/10484067/TeamLink_2_0_0_2_managed.zip)

Could you try this version please to see if that fixes it.  It should work up to 999 team members now. @slickspidey

**Comment by slickspidey** [comment]
Hi @stuartridout, I just installed it but now it's showing significantly fewer members than before. Previously, the list would display team members with names starting from "A" to "T", but now it is only showing members from "A" to "N".

**Comment by stuartridout** [comment]
How many team members are there in the Team?

**Comment by stuartridout** [comment]
[TeamLink_2_0_0_3_managed.zip](https://github.com/stuartridout/teamlink/files/10488502/TeamLink_2_0_0_3_managed.zip)

Let's try again @slickspidey ... for some strange reason I had restricted the results to the first 90.

**Comment by slickspidey** [comment]
@stuartridout I have a team of 117 people right now. We can see everyone now, that's perfect! Thank you! 

I am trying to use MS Power BI to create a table that displays the office presence status of employees in my organization, as recorded in the "cr599_presence" table in MS Dataverse. However, the table is showing inflated numbers for some employees and I am not sure why. I am trying to show a count of the unique presence entries for each staff member, but some are showing more than the expected 5 entries for a week. Can you help me understand why this is happening or how to correctly show the count of presence entries for each employee? I have included an image for reference.
![Screenshot 2023-01-24 092255](https://user-images.githubusercontent.com/25755070/214349216-f52eeed3-ba6d-40d5-8615-184c2aef79a7.png)

**Comment by stuartridout** [comment]
Can you raise a new issue for this one. 

Thanks
