### ISSUE TITLE
Hide Avatars option

### ISSUE THREAD

**Issue by tdashworth** [stuartridout/teamlink#5]
Firstly, thank you Stuart for creating this app. We are just about to trial the app in a Team of about 50 members. 

We have made a few changes to the app to support the team's management structure (which I'll suggest in a separate issue) and the performance has been significantly impacted due to the many Office365 requests. 

Our solution so far has been to remove the user's avatars. I was wondering if this could become a setting on the admin screen?

**Comment by stuartridout** [comment]
Thanks for your kind words.  I'll add this to the backlog.
