### ISSUE TITLE
Edit Presence and View Any Team screen not updating

### ISSUE THREAD

**Issue by Markus-F** [stuartridout/teamlink#51]
We are facing issues, where the screen is not updating correctly. If users enter new data it is entered in the relevant tables but not shown in the app itself. Any ideas?

**Comment by stuartridout** [comment]
Hi there.  Can you provide more detail please?

Which version?
What screen?
Where is it not being shown?
Screenshots 
Is it Dataverse for Teams? 
Is it just being used in a Team or shared more widely with members outside of the team?

**Comment by Markus-F** [comment]
Hi Stuart,

it's version 2.0.0.3 but I have seen that there has been an update to that version 2 days ago? I will update it once more.  

The screen is the "My calendar" screen and the "Pinned List" view. The rows are empty for some users although they have entered something for the next days. 

We are using Dataverse for Teams and the app is used only with members of the team it was published to (10 user).

Best regards,
Markus

**Comment by Markus-F** [comment]
The update seems to have fixed the issue.
